### ISSUE TITLE
BulkFuture epic fail !!! false : false : false

### ISSUE THREAD

**Issue by kieranbenton** [mathieuancelin/play2-couchbase#33]
We're trying to use play2-couchbase in a play2/scala project that is designed for high-concurrency (and is mostly fully async) but we've run into a pretty major issue that we're finding hard to understand ourselves. We _think_ its with the play2-couchbase library and not the underlying java client but we're not totally certain. 

Basically if we do:

```
val futureP = Future.sequence(Seq(
        bucket.get[SessionSeen](key1),
        bucket.get[SessionStatus](key2),
        bucket.get[SessionStatus](key3)
    ))
```

(or a variation, I've tried doing a `fetch` as well to attempt to do a couchdb bulk get)

Then _sometimes_ (reproducibly under some simple load - applied using apachebench) we get either (depending on our config as described in your docs) get the INFO log line about `BulkFuture` or a full blown stack-trace, see below. This (on windows at least) seems to result in eventual thread starvation and my service grinding to a halt.

Now I've tried to figure out exactly what is going on here but I can't find any hints as to exactly what the purpose of `BulkFuture` or its interaction with `CouchbaseFutures` is. I've tried adding some additional logging to a fork of play2-couchbase but I'm not getting very far quickly.

Can you help me fill in the blanks? Would happily help fix/debug and provide a PR but at the moment I'm at a bit of a loss.

Merry Christmas and thanks!

```
play.api.Application$$anon$1: Execution exception[[Throwable: BulkFuture epic fail !!! false : false : false]]
    at play.api.Application$class.handleError(Application.scala:293) ~[play_2.10.jar:2.2.1]
    at play.api.DefaultApplication.handleError(Application.scala:399) [play_2.10.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:165) [play_2.10.jar:2.2.1]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$12$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:162) [play_2.10.jar:2.2.1]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33) [scala-library.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:185) [scala-library.jar:na]
    at scala.util.Try$.apply(Try.scala:161) [scala-library.jar:na]
    at scala.util.Failure.recover(Try.scala:185) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:387) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:387) [scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
    at play.api.libs.iteratee.Execution$$anon$1.execute(Execution.scala:43) [play-iteratees_2.10.jar:2.2.1]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37) [scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133) [scala-library.jar:na]
    at scala.concurrent.Promise$class.complete(Promise.scala:55) [scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:254) [scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:249) [scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67) [akka-actor_2.10.jar:2.2.0]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82) [akka-actor_2.10.jar:2.2.0]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.10.jar:2.2.0]
    at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59) [akka-actor_2.10.jar:2.2.0]
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library.jar:na]
    at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58) [akka-actor_2.10.jar:2.2.0]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) [akka-actor_2.10.jar:2.2.0]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) [akka-actor_2.10.jar:2.2.0]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
Caused by: java.lang.Throwable: BulkFuture epic fail !!! false : false : false
    at org.ancelin.play2.couchbase.client.CouchbaseFutures$$anon$1.onComplete(CouchbaseFutures.scala:28) ~[play2-couchbase-kb_2.10.jar:0.7-SNAPSHOT]
    at org.ancelin.play2.couchbase.client.CouchbaseFutures$$anon$1.onComplete(CouchbaseFutures.scala:19) ~[play2-couchbase-kb_2.10.jar:0.7-SNAPSHOT]
    at net.spy.memcached.internal.AbstractListenableFuture$1.run(AbstractListenableFuture.java:119) ~[spymemcached-2.10.2.jar:2.10.2]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_40]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) ~[na:1.7.0_40]
    ... 6 common frames omitted
```

Environment
- Windows 8 x64 - dual core
- Scala 2.10.2 (running Java 1.7.0_40)
- Play 2.2.1
- SBT 0.13.0

**Comment by mathieuancelin** [comment]
Hi,

I assume you're using the last version of play2-couchbase (0.6 or 0.7-SNAPSHOT). If not, can you tell me the version of the plugin you're using ?

Also, can I see the couchbase configuration part of your application ?

Is it only reproducible under load ? or it happens all the time ?

Thanks for your answers

**Comment by mathieuancelin** [comment]
Can try with the following configuration : 

couchbase.driver.checkfuture=false

**Comment by mathieuancelin** [comment]
Actually this particular error says that the Future returned by the actual Couchbase Java Client told the play2 plugin that the operation is complete but when the plugin ensure that the work is actually done, the values of the future are : 
- future.isDone == false
- future.isCancelled == false
- future.isTimeout == false

which is super strange. That's why the fail is Epic (according to me)

With `couchbase.driver.checkfuture=false` the plugin will not worry about that, but I'm not sure it's a good sign either but if it's a bug with Couchbase CompletableFutures, despite a log warning, it should work.

**Comment by kieranbenton** [comment]
Yes that's why I'm hesitant to just turn `couchbase.driver.checkfuture=false` as I think its likely hiding a problem :) As I said I'm getting thread exhaustion too under load.

Sorry, should have said versions! Yes I'm running 0.6 (and I've tried building from master too, 07-SHAPSHOT?).

Later today I will try building a small program to reproduce the issue that I can share with you.

Cheers!

**Comment by mathieuancelin** [comment]
Cool :-) It will be easier to find the issue.

To me, the epic fail error comes from Couchbase client. 
But if you have thread exhaustion, I'm very curious to know what is happening.

**Comment by kieranbenton** [comment]
Right, its taken a while (sorry!) but I've got this down to a pretty tiny test case now. I've upgraded it to 0.7-SNAPSHOT as well.

https://www.dropbox.com/sh/c8qh20qjx7l63p1/1WpvlRv-PK

You'll need to set a local bucket up called 'test' (or tweak conf\application.dev.conf). I've turned OFF `couchbase.driver.checkfuture` just so that my logs dont fill up as quickly :)

If you hit:
`http://localhost:9000/prime` - to just create the sample documents the test requires

Then:
`http://localhost:9000/test` - to trigger the error

Now, if you bash F5 for long enough and at varying rates then you will eventually get the error message - but a much easier way to see the problem is with apache bench.

So if you do:
`& 'C:\Program Files (x86)\Apache Software Foundation\Apache2.2\bin\ab.exe' -n 10000 -c 4 http://localhost:9000/test`

You should almost immediately start to see the INFO log lines (as you can see the combination of flags logged varies). Screenshot at the bottom. _Sometimes_ this results in AB never being able to finish its test run and CPU dropping to nothing as I assume all the JVM threads are hung up on futures (I've not dug any deeper on this yet).

Now - I'm on Windows 8.1 x64, 8GB + dual core, from some anecdotal evidence from a colleague of mine this may _NOT_ be reproducible on Mac OSX at least, so it may even be platform specific? Not 100% sure though.

Anything else you need or want me to try - please just ask!

![capture](https://f.cloud.github.com/assets/39090/1798225/1b2bc644-6b36-11e3-9d29-f3f9febee4e8.PNG)

**Comment by mathieuancelin** [comment]
Based on the first tests I've done, I cannot reproduce the issue.

I clearly have the messages but as I said earlier, I think it's mostly a Couchbase Client issue in the CompletableFutures part (maybe a synchronization issue or something like that, but it doesn't seems to affect the operation itself (meaning data are here :-). I'll try to investigate more and see with the Couchbase guys.

But I wasn't able to reproduce the Thread exhaustion issue (I'm on OSX). I quickly profiled the application with VisualVM and indeed, with the provided configuration, the calls to the Couchbase server are stacked very quickly to be processed asap. The result is that the number of live thread is very high and maybe it's what causing you issues.

You can try to play with the parallelism factor of the couchbase-plugin threadpool and see what's happening (then you can tune it to fit your need depending on the environment). I tried with something like : 

```
execution-context {
    fork-join-executor {
        parallelism-factor = 5.0 # that's the important part
        parallelism-max = 50
    }
}
```

and the result was pretty nice.

You can use http://doc.akka.io/docs/akka/snapshot/general/configuration.html to tune the threadpool.

Let me know if it's better with a bit of tuning.

**Comment by kieranbenton** [comment]
I'm still having issues with ab hitting a couple of 1000 requests and then stalling completely - but will have a play with the ec settings.

Thanks for the tips about the ec configuration - I will experiment a bit, maybe switching to the threadpool executor might work better on Windows.

Do you think that the bulkfuture INFO log line is a bug in the couchbase client then? I'm still struggling to understand the role of a BulkFuture in all of this :) Is that a method they use to batch multiple requests together and then notify a client of the individual status of requests? Is any of that documented anywhere (just so I can learn about it if nothing else).

Do you recommend running play2-couchbase in a seperate EC from play2 then or is all-in generally the best configuration?

Cheers.

**Comment by mathieuancelin** [comment]
I'm sure it's going to be better with a more reasonable parallelism-factor. 

You can also try with a `thread-pool-executor` instead of a `fork-join-executor` because you can tune it very precisely. Everything is explain in the Akka documentation (http://doc.akka.io/docs/akka/snapshot/general/configuration.html#akka-actor).

About the BulkFuture, it's a mechanism provided by Couchbase to represent an async BulkGet operation (when you do a get with play2-couchbase, it's actually a BulkGet). There are many Future types in Couchbase java client to support all kind of operations. These Future types provides a way to be notified when the future is done.

The log message comes from a part I wrote in play2-couchbase to bridge Couchbase CompletableFutures and Scala Futures. In that part, when the plugin is notified that a future is done, cancelled or timeout, I try to check if it's actually true. If not, then the log message is displayed (or an exception is thrown). But it seems that despite the flags (done, cancel, timeout) being wrong, the operation is still a success and it's possible to get the returned value of the operation. So I guess it's a Couchbase client issue, but not totally sure. The code to bridge Couchbase Future types is available here : https://github.com/mathieuancelin/play2-couchbase/blob/master/plugin/src/main/scala/org/ancelin/play2/couchbase/client/CouchbaseFutures.scala

If you provide an `execution-context` part in the configuration, then play2-couchbase use a separate EC for the future bridge part. But depending on what implicit EC you provide in your code for couchbase operations, all your callbacks will be executed in that EC. I think it's better to use the play2-couchbase EC (`Couchbase. couchbaseExecutor`) for that because you can tune it precisely according to your needs. But the Play default EC can be just fine, its default configuration is the following

```
default-dispatcher = {
   fork-join-executor {
      parallelism-factor = 1.0
      parallelism-max = 24
   }
} 
```

**Comment by kieranbenton** [comment]
Thanks for your advice Mathieu, it is much appreciated!

One other thing, when I put load on my app in a different way (which doesn't actually use couchbase `get`, but rather `incrAndGet`) I have zero issues and very low latency, which makes me still a little worried that there is a racing bug somewhere in that I can fairly reliably lock-up my app.

But anyway, I'll let you know how my tweaking of ECs goes. You might still want to try and reproduce it on Windows though, I could maybe send you a VM if thats easier for you?

I'll keep the ECs for play and play2-couchbase separate and see where that gets me.

Thanks!

**Comment by mathieuancelin** [comment]
I think I got it.

When a BulkGetFuture is done (https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/protocol/binary/OperationImpl.java#L203) the driver will first set the status (https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/protocol/binary/OperationImpl.java#L259) then complete the operation (https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/protocol/binary/OperationImpl.java#L205, https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java#L141). It will trigger receivedStatus (https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/MemcachedClient.java#L1259) that will trigger the callback notification (https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/internal/BulkGetFuture.java#L185) then unlock the future (https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/MemcachedClient.java#L1269). But as you can see, the future flags (done, cancel) are based on the CountDownLatch of the future (https://github.com/dustin/java-memcached-client/blob/master/src/main/java/net/spy/memcached/internal/BulkGetFuture.java#L195) which is set after the callback notification. So it explain why sometimes I have to print the error message or throw an Exception because flags are not set yet. We were lucky that it didn't appear much more often.

I will check with Couchbase guys if it's actually an issue on their side or if my plugin is a bit too much paranoïd ;-)

About the threading issue, to me it's definitely on the play2-couchbase side and I guess it's mostly a configuration issue, too much parallel operations on live threads. About testing on Windows, I won't be able to test it on a VM until the end of the holidays (low bandwidth internet connection here). But I will try your sample with a very heavy load (with Gatling tool) and different configurations.

**Comment by kieranbenton** [comment]
Well thats pretty excellent news!

Sadly I'm still struggling here - I've seperated the ECs of play, play2-couchbase and the driver out (assuming that is what `couchbase.driver.useec = false` does?), configured the plugin as:

```
couchbase {
    json.validate = true # JSON structure validation fail
    failfutures = true # fail Scala future if OperationStatus is failed
    useplayec = false # force play2-couchbase to use its own akka execution-context
    driver {
        useec = false # use couchbase-executioncontext as ExecutorService for couchbase driver
        checkfuture = false # makes sure that the bulkfuture errors get thrown
    }
    execution-context {
        execution-context {
             fork-join-executor {
                parallelism-min = 8
                parallelism-factor = 5.0 # used to determine thread pool size using the following formula: ceil(available processors * factor). Resulting size is then bounded by the parallelism-min and parallelism-max values.
                parallelism-max = 64
             }
         }
    }
}
```

And still no luck.

After digging a bit further though, I don't think its actual exhaustion I'm getting. Basically my `ab` test will just stall after (usually) several thousand requests, and will never complete waiting for responses. Hitting Ctrl+C will then show most of the completed requests completing just fine but then a couple open still waiting.

I've tried the very unscientific method of trying to hit the app from a browser at the same time as `ab` is stuck and requests complete ok, so the whole app isnt totally stalled.

I'm a bit of a loss as to what to try next though, I'm not very good with VisualVM and Scala yet - so not sure that will tell me any more!

Any ideas/pointers? Or anything else I can do to help you diagnose the issue?

**Comment by mathieuancelin** [comment]
I already have some issues with `ab` at the time. 

So now for load test, I use Gatling tool (http://gatling-tool.org/)

I guess a scenario like (for version 1.5.3) : 

``` scala
package couch

import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.jdbc.Predef._
import com.excilys.ebi.gatling.http.Headers.Names._
import akka.util.duration._
import bootstrap._

class CouchSimulation extends Simulation {

    val httpConf = httpConfig
        .baseURL("http://localhost:9000")
        .acceptCharsetHeader("ISO-8859-1,utf-8;q=0.7,*;q=0.7")
        .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
        .acceptEncodingHeader("gzip, deflate")
        .acceptLanguageHeader("fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3")
        .disableFollowRedirect

    val scn = scenario("Test couchbase plugin").repeat(200) {
        exec(http("TestRequest").get("/test")).pause(0 milliseconds, 1 milliseconds)
    }
    setUp(scn.users(200).ramp(10).protocolConfig(httpConf))
}
```

would be enought. Here you simulate 200 users doing 200 request on the test URL. I used the same configuration as you provided (for thread pools) and it works fine. 

And to investiguate, I guess VisualVM is the right tool if you're not confortable with more bare metal tools, it's actually a pretty tool in my opinion. The first thing you can do is run your play app, connect visual VM on it (from the Local application tree) and go to the `Monitor` tab. Then you can watch how is evolving the threads of your app when your run your load tests. If you want a more precise view of the state of your threads, just go to the `Threads` tab. 

Let me know if you find something or have issues.

**Comment by kieranbenton** [comment]
Yes - I thought that gatling might be the best tool to use :) I've tried it now based upon your simulation and I get pretty much the same behaviour as with `ab`... :/

Say out of 10,000 requests (200 users x 50 tests per user) I get 9994 'good' and 6 'bad' (timeouts). I could send you the gatling report if that helps? 

https://www.dropbox.com/s/f9yade24rld7kxa/couchsimulation-20131223181925.zip

Urls being hit are slightly different as this is my 'non-cut-down' app instead of the mini-test.

The higher the concurrency the worse the failure rate it seems.

Again if I use the 'non-get' code path then I get 100% success rate - matching what I've seen with `ab`.

Gatling scenario is:

```
package couch

import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.jdbc.Predef._
import com.excilys.ebi.gatling.http.Headers.Names._
import akka.util.duration._
import bootstrap._

class CouchSimulation extends Simulation {

val httpConf = httpConfig
    .baseURL("http://localhost:9000")
    .acceptCharsetHeader("ISO-8859-1,utf-8;q=0.7,*;q=0.7")
    .acceptHeader("text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
    .acceptEncodingHeader("gzip, deflate")
    .acceptLanguageHeader("fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3")
    .disableFollowRedirect

// 200 users nudging 50 times = 10000 requests

val scn1 = scenario("NewNudge").repeat(50) {
    exec(http("TestRequest")
      //.get("/nudge/blah"))
        .get("/nudge/blah?session_id=7bf655ca-5ba0-424f-8f17-11f9cb649eef")
    ).pause(0 milliseconds, 1 milliseconds)
}

setUp(scn1
    .users(200) // 200 concurrency
    .ramp(10)
    .protocolConfig(httpConf)
)

}
```

**Comment by kieranbenton** [comment]
Seems like it must be a platform related issue then?

**Comment by mathieuancelin** [comment]
That's really weird !!! The curves on the simulation shows that something is really going wrong ...

I'll try to test it on Windows ASAP

**Comment by kieranbenton** [comment]
Yeah I'm beginning to think I'm going mad :)

How about I set a EC2 VM up that you could log into? Probably won't be able to get that done today though.

EDIT: I've retried the 'small test' app on my box just to make sure I'm still getting the same there as well - and I am. Full copy of the test app, gatling script and a test run result (9993 ok, 7 failures!) included here:

https://www.dropbox.com/sh/sd7uvqx44yumvvt/UWZUUPh97d

I can try and get that stood up on EC2 if you like - just let me know. Thanks again - you've been very helpful!

**Comment by mathieuancelin** [comment]
I Will try to run your tests as is and see what happens

And don't worry for the EC2 instance, I won't be really available for the next 3 days. So don't rush :-)

**Comment by kieranbenton** [comment]
Of course :) merry christmas!

**Comment by mathieuancelin** [comment]
Thanks ! Merry Christmas too !

**Comment by kieranbenton** [comment]
Happy new year Mathieu!

I've noticed the project has completely changed structure? Should I move to the new packages and retry my tests? Or have you managed to make any further progress in identifying the problem?

Cheers.

**Comment by mathieuancelin** [comment]
Hi,

Happy new year !

Actually I've renamed the project, split it in many modules to use the driver outside of Play, etc ...

You can have a look at http://reactivecouchbase.org/ now

You can migrate your project with https://github.com/ReactiveCouchbase/ReactiveCouchbase-play and see what happens, but it shouldn't change anything for you (except packages name and some APIs name)

Tell me if you encounter migration issues

**Comment by kieranbenton** [comment]
Yes - I've just been porting to the new package, `"org.reactivecouchbase" %% "reactivecouchbase-play" % "0.2-SNAPSHOT"`.

So far so good, though I've noticed that the plugin isn't logging to the `ReactiveCouchbase` logger like it seems like it should be? Its going to `application` instead?

In terms of the performance/lockup issues I'm having - yes they are still present :( shall I arrange to get an EC2 instance setup for you to see it in action?

**Comment by mathieuancelin** [comment]
Nice catch. I've just pushed a fix for the logger name.

Too bad you still got performance issue. Before setting up an EC2 instance, I'll try to see if I can get a Windows machine at work to make some test on Monday

**Comment by kieranbenton** [comment]
Ok cool - thanks!

**Comment by kieranbenton** [comment]
That's mostly worked. I am however still getting:
`[application] Failing on bad JSON structure enabled.`
(twice actually) though.

Think thats ReactiveCouchbase right?

Did you have any luck with a Windows machine?

Cheers,
Kieran

**Comment by daschl** [comment]
@kieranbenton looks like this is an issue in spymemcached and the couchbase sdk. I'll work with mathieu to get this fixed asap.

**Comment by kieranbenton** [comment]
Thanks @daschl, if you need any help or test cases confirming please just let me know.

**Comment by daschl** [comment]
@kieranbenton java client 1.3.0 has been released which should hold a fix for this. Let's wait until @mathieuancelin upgrades and then hopefully its fixed.

If not, we need to work further to track this down, but early tests did show indeed its much better now.

**Comment by mathieuancelin** [comment]
Hi,

just tried the last plugin version (with client 1.3.0) with gatling on windows (with the play start command) and it went pretty well. No more weird log error.

I will publish the plugin tonight so you can test it.

**Comment by kieranbenton** [comment]
Thanks Mathieu - did you manage to republish 0.2-SNAPSHOT or should I wait?

Cheers.

**Comment by daschl** [comment]
@kieranbenton you can wait or, just to test, in theory you could replace the jars with the new ones - there was no API breakage or so going on

**Comment by mathieuancelin** [comment]
I didn't have the time yesterday.

Hopefully, I'll push everything tonight.

**Comment by kieranbenton** [comment]
No problem Mathieu - thanks again!

**Comment by mathieuancelin** [comment]
@kieranbenton I've pushed a new 0.2-SNAPSHOT. Can you test it please ? and don't forget to use `play start` for load testing

**Comment by kieranbenton** [comment]
Hi Mathieu,
I've been trying to update to the 0.2-SNAPSHOT version of
`reactivecouchbase-play` but I'm having problems. No matter what I do - it
references `reactivecouchbase-core_2.10;0.1-SNAPSHOT` instead of
0.2-SNAPSHOT.

Looking at the pom file at
https://github.com/ReactiveCouchbase/repository/blob/master/snapshots/org/reactivecouchbase/reactivecouchbase-play_2.10/0.2-SNAPSHOT/reactivecouchbase-play_2.10-0.2-SNAPSHOT.pom
I
can;t see why this would be - can you shed any light?

Cheers,
Kieran

**Comment by mathieuancelin** [comment]
Hum, that's strange. You can try to run the `reload` command in your project.

You can also go to `${PLAY_HOME}/repository/cache` and `${PLAY_HOME}/repository/local` to remove `org.reactivecouchbase` folders.

And if it doesn't work, I really don't know what's happening.

**Comment by kieranbenton** [comment]
Ah - my fault, had a subtly wrong repo setup, I've managed to refresh it now and got the latest bits.

Well, its certainly better! I don't get the same pattern of logs as I have done previously which is brilliant.

I do still get some strange issues. I'm still occasionally (not as often I think) having single request lockups like before... will try and experiment further. Also, some separate sockets code (UDP) that is publishing some metrics to OpenTSDB for me is now complaining after a bit of a soak test about being unable to connect. I will explore that further and try and rule the cb code out (though this has only appeared after just updating the libraries).

I'm getting some new log lines quite regularly:
`DEBUG (Finalizer) [com.ning.http.client.AsyncHttpClient] AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks`
`DEBUG [c.n.h.c.p.n.NettyAsyncHttpProvider] Number of application's worker threads is 8`

Does that mean anything to either of you?

**Comment by mathieuancelin** [comment]
Yes, I need to do some Logger configuration work on the current snapshot. Hopefully, it will disappear soon.

**Comment by kieranbenton** [comment]
Ok - I'll leave it for now and do some more soak testing, see if I can dig up any more issues. 

I've just got:

```
WARN  [c.c.client.internal.ViewFuture] Exception thrown wile executing org.reactivecouchbase.client.CouchbaseFutures$$anon$5.operationComplete()
java.lang.IllegalStateException: Promise already completed.
    at scala.concurrent.Promise$class.complete(Promise.scala:55) ~[scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:58) ~[scala-library.jar:na]
    at scala.concurrent.Promise$class.success(Promise.scala:89) ~[scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.success(Promise.scala:58) ~[scala-library.jar:na]
    at org.reactivecouchbase.client.CouchbaseFutures$$anon$5.onComplete(CouchbaseFutures.scala:188) ~[reactivecouchbase-core_2.10-0.2-SNAPSHOT.jar:0.2-SNAPSHOT]
    at org.reactivecouchbase.client.CouchbaseFutures$$anon$5.onComplete(CouchbaseFutures.scala:181) ~[reactivecouchbase-core_2.10-0.2-SNAPSHOT.jar:0.2-SNAPSHOT]
    at net.spy.memcached.internal.AbstractListenableFuture$1.run(AbstractListenableFuture.java:119) ~[spymemcached-2.10.4.jar:2.10.4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_40]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_40]
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:42) [akka-actor_2.10-2.2.0.jar:2.2.0]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386) [akka-actor_2.10-2.2.0.jar:2.2.0]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library.jar:na]
```

Which looks like it might still be a similar issue to the original problem?

Thanks!

**Comment by daschl** [comment]
@kieranbenton that's a different issue you are running into. Actually a regression for 1.3.0 that has been fixed on master. I plan to do a quick 1.3.1 tomorrow.

The issue is that ViewFutures are completed twice (the listeners are notified twice), but the scala promise has hiccups when you try to notify it twice.

See http://www.couchbase.com/issues/browse/JCBC-399

**Comment by mathieuancelin** [comment]
It's a brand new  driver bug. It should be fixed soon. 

https://github.com/ReactiveCouchbase/ReactiveCouchbase-core/issues/3

**Comment by kieranbenton** [comment]
Thanks guys :) if I find any more issues I'll let you know!

Is there anything I can do to try and contribute some tests to cover these cases? Seems like we're giving both reactive and the driver a pretty good work out?

**Comment by mathieuancelin** [comment]
You can send PRs on ReactiveCouchbase-core tests or ReactiveCouchbase-play tests (doesn't exist yet).

**Comment by kieranbenton** [comment]
Sadly, I've got to report I'm still having the same issue. The `BulkFixture` errors are eliminated - but my code path with the `gets` in it still eventually results in the same behaviour as before, most requests complete fine but a small percentage essentially hang and never complete.

Just to confirm, I've used `play start` (no difference) and tried using both `ab` and `gatling`. The code path with all incr/sets works fine but as soon as I start doing reads weird things happen :(

Did you guys manage to see a difference when running my minimal test case?

**Comment by mathieuancelin** [comment]
Hi,

as that Issue seems to be tenacious, I'll try to have a deep look at it during the weekend.

@kieranbenton can you send me a Play project with the minimum operations needed to reproduce the issue on your computer ? Can you also give me tests scenario with `ab` and `gatling` ?

I'll try to provide you custom versions of ReactiveCouchbase to see if something changes on your environment if I can't reproduce the issue.

Thanks in advance

**Comment by daschl** [comment]
Let me know if I can help SDK-wise or with couchbase internals!

**Comment by mathieuancelin** [comment]
@daschl no problem ;-)

**Comment by kieranbenton** [comment]
Thanks guys - really appreciate it!

I've updated my minimal repro case and its all here:
https://www.dropbox.com/sh/xjf49ntgwisqkyj/JFD5kiVeob

App is pretty much the same as before Mathieu - I've added a test case for
bucket.set as well now but thats it.

I have added a gatling script to /test and two powershell scripts to run
the test cases using both ab and gatling.

I should say that VERY occasionally the test cases complete correctly - so
if it happens to you please make sure you run them a few times to see the
issue. I can send you my gatling outputs if you still can't see it.

Behaviour is very much the same still, vast majority of requests work fine
out of 10k, but a few lockup and never return to the client.

Anything else - please let me know.

Cheers,
Kieran

**Comment by mathieuancelin** [comment]
I moved the issue here : https://github.com/ReactiveCouchbase/ReactiveCouchbase-core/issues/5
